### ISSUE TITLE
No plugins showing up in Orchestra Pit plugins list

### ISSUE THREAD

**Issue by jistr** [flathub/fm.helio.Workstation#1]
First, thanks for making a flatpak build of this interesting tool.

I can't seem to make any plugins show up in the Orchestra Pit, even after scanning a custom folder. Since the app has "filesystem=home" permission, not being able to access the files shouldn't be the problem.

I saw at https://github.com/helio-fm/helio-workstation/issues/189 that folks were having issues with some instrument plugins and tried to go for the suggested approach of using JackAss to export MIDI and set up plugins in Carla, but even JackAss isn't recognized.

**Comment by hfiguiere** [comment]
I use the flatpak plugins (branch 22.08 at the moment).

![image](https://github.com/flathub/fm.helio.Workstation/assets/114441/aac3ca5b-2fbc-4c3e-b567-81bb9f45708c)

**Comment by hfiguiere** [comment]
![image](https://github.com/flathub/fm.helio.Workstation/assets/114441/66d4e002-a418-4f17-a111-5e5bba34f50d)

**Comment by hfiguiere** [comment]
The only reason it has `home` permission is that plugins randomly write data there and there is no mechanism to allow access ad-hoc.

**Comment by hfiguiere** [comment]
> I use the flatpak plugins (branch 22.08 at the moment).

With #3 that will be 23.08.

**Comment by hfiguiere** [comment]
I don't know what "JackAss" is beside a slur, but it's not in the plugins available for flatpak.

**Comment by jistr** [comment]
Yea i have both 22.08 and 23.08 instrument plugins installed currently but nothing's showing up, just the spinner that disappears after a while. I wonder if some bad plugin could be blocking the scanning perhaps... There is no output on stdout/stderr when i run Helio from console and it doesn't look like it has any other logging facility. I'll try to poke around a bit more to figure it out. Thanks for your replies.

**Comment by jistr** [comment]
![image](https://github.com/flathub/fm.helio.Workstation/assets/331840/38e36b40-50fb-4e68-8fb3-81cb98c98969)

**Comment by jistr** [comment]
More info: I built the flatpak locally from Helio's `develop` branch with no improvement, then i also added `CONFIG=Debug` and i'm getting these JUCE assertion errors, both on common dirs scan:

```
[... previous output skipped ...]
Safe scanning: /app/extensions/Plugins/vst3/CardinalSynth.vst3
JUCE Assertion failure in juce_posix_SharedCode.h:1100
Safe scanning: /app/extensions/Plugins/vst3/CardinalFX.vst3
JUCE Assertion failure in juce_posix_SharedCode.h:1100
Safe scanning: /app/extensions/Plugins/vst3/Cardinal.vst3
JUCE Assertion failure in juce_posix_SharedCode.h:1100
Safe scanning: /app/extensions/Plugins/vst3/BYOD.vst3
JUCE Assertion failure in juce_posix_SharedCode.h:1100
Done scanning for audio plugins
```

and custom dir scan:

```
Safe scanning: /var/home/jistr/.vst/jackass.vst/JackAss.so
JUCE Assertion failure in juce_posix_SharedCode.h:1100
Safe scanning: /var/home/jistr/.vst/jackass.vst/JackAssFx.so
JUCE Assertion failure in juce_posix_SharedCode.h:1100
Done scanning for audio plugins
```

The assertion error points here:

https://github.com/peterrudenko/JUCE/blob/helio/3.11/modules/juce_core/native/juce_posix_SharedCode.h#L1100-L1101

**Comment by jistr** [comment]
So since strace didn't go towards a solution, i tried launching helio through GDB in hope of being able to perhaps get the stack trace of what is failing to execute there, and... the scanning worked!

```
flatpak run --devel --command=bash fm.helio.Workstation -c 'gdb helio'
```
and then in GDB:

```
run
```

Some funny observations:

* Now that the plugins are scanned and saved in `~/.config/Helio/settings.helio`, i can start Helio normally (without going through GDB) and i can create instruments with the plugins normally.

* If i wanted to rescan or add more plugins, i would have to go through `gdb` again, the scanning itself is still broken otherwise.

So maybe your plugin list was just scanned previously, and if you were to backup and remove your `settings.helio` to start with an empty config on the latest build, you might hit the same issue... (Not suggesting you should do that tho :) ).

**Comment by jistr** [comment]
Got it. Helio is actually trying to launch itself as a child process, and it requires to be launched using an absolute path, regardless if `helio` is on `$PATH` or not. This could be a limitation of JUCE rather than Helio maybe. Fix incoming.

**Comment by jistr** [comment]
I also reported this upstream, i think at least a clear error message would be good in this case. https://github.com/helio-fm/helio-workstation/issues/280
