### ISSUE TITLE
JACK output not working on Fedora Silverblue 38

### ISSUE THREAD

**Issue by jistr** [flathub/fm.helio.Workstation#2]
It seems i can only get Helio to produce some sound with the ALSA output plugin. When i switch to JACK, there is just silence. I also use Ardour in flatpak and that works fine with JACK output.

**Comment by hfiguiere** [comment]
I think it's a pipewire regression.

Updating to 23.08 works.

**Comment by jistr** [comment]
Indeed it works now, thanks for the quick fix!
